### ISSUE TITLE
Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by Tijani891** [BolajiAyodeji/image-search-app#50] opened 2022-08-31 21:24 UTC
I analysed your webpage with Lighthouse and I discovered that the logo image does not have `alt` attributes. I would love to fix this

![open source](https://user-images.githubusercontent.com/105027115/187787542-a183f9e5-be32-407b-a113-ea7eb5d02bf3.PNG)

**Comment by BolajiAyodeji** [comment] 2023-01-27 10:02
Thanks for raising this issue! The issue is already fixed in #21. I'd be closing this now; thank you.

**Closed by BolajiAyodeji** 2023-01-27 10:02 UTC
