### ISSUE TITLE
Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by Basheer-Ade** [BolajiAyodeji/image-search-app#36] opened 2022-08-12 21:02 UTC
I tried to analyze the website and realized that the logo image does not have `alt` text. I would like to fix this.
![image](https://user-images.githubusercontent.com/105149502/184444459-dd212fc6-0214-4303-901b-1bfe778caf1c.png)

**Comment by michado2019** [comment] 2022-08-31 11:43
I tried analyzing your app but your logo-image element doesn't not have [alt] attribute. I'd like to fix it
![Screenshot (22)](https://user-images.githubusercontent.com/104470728/187670600-38ae9c5e-16dc-491a-894c-9e784e3bc1d0.png)

**Comment by BolajiAyodeji** [comment] 2023-01-27 10:04
Thanks for raising this issue! The issue is already fixed in #21. I'd be closing this now; thank you.

**Closed by BolajiAyodeji** 2023-01-27 10:04 UTC
