### ISSUE TITLE
Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by thebenjaminibe** [BolajiAyodeji/image-search-app#45] opened 2022-08-17 06:17 UTC
I tried to analyze your website using Lighthouse and realized that the logo image does not have an 'alt' text. I'd like to fix this.

![img](https://user-images.githubusercontent.com/97017874/185047658-80edbd03-37d7-4e4c-ab03-a7edee7e5d32.png)

**Comment by BolajiAyodeji** [comment] 2023-01-27 10:03
Thanks for raising this issue! The issue is already fixed in #21. I'd be closing this now; thank you.

**Closed by BolajiAyodeji** 2023-01-27 10:03 UTC
