### ISSUE TITLE
 Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by mrfantastic16** [BolajiAyodeji/image-search-app#53] opened 2022-09-20 10:26 UTC
I tried to analyze your website and realized that your log image does not have an `alt` attribute. I'd like to fix this

**Comment by BolajiAyodeji** [comment] 2023-01-27 10:01
Thanks for raising this issue! The issue is fixed already in #21. I'd be closing this now; thank you.

**Closed by BolajiAyodeji** 2023-01-27 10:01 UTC
