### ISSUE TITLE
Image element does not have [alt] attribute

### ISSUE THREAD

**Issue by Jiouras** [BolajiAyodeji/image-search-app#52] opened 2022-09-08 12:04 UTC
I tried to analyze your website and realized that the logo image does not include an alt text. I would like to fix this 

![Screenshot (14)](https://user-images.githubusercontent.com/106819948/189117000-3df8c09e-2d2b-43d7-9f06-9c1f598b3ba4.png)

**Comment by BolajiAyodeji** [comment] 2023-01-27 10:02
Thanks for raising this issue! The issue is fixed already in #21. I'd be closing this now; thank you.

**Closed by BolajiAyodeji** 2023-01-27 10:02 UTC
